// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaxcJK5FYO2RINmUjQ6xPu067_lFqzJSw',
    appId: '1:393576484737:web:6e63f76928606c2cbfa280',
    messagingSenderId: '393576484737',
    projectId: 'dietifyy-66388',
    authDomain: 'dietifyy-66388.firebaseapp.com',
    storageBucket: 'dietifyy-66388.firebasestorage.app',
    measurementId: 'G-JREQ5JF2YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUHv7uwVOnA02pRHYxsXtt_ZSAGO2qu7w',
    appId: '1:393576484737:android:0f71832540840d53bfa280',
    messagingSenderId: '393576484737',
    projectId: 'dietifyy-66388',
    storageBucket: 'dietifyy-66388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1WtEBqNXNfDRY7rX_NLhGd-Vq1jOPd4o',
    appId: '1:393576484737:ios:f894c1fe62074d01bfa280',
    messagingSenderId: '393576484737',
    projectId: 'dietifyy-66388',
    storageBucket: 'dietifyy-66388.firebasestorage.app',
    iosClientId: '393576484737-762pbsgs7fjq2enm8fckq4ckemp1q09n.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietifyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1WtEBqNXNfDRY7rX_NLhGd-Vq1jOPd4o',
    appId: '1:393576484737:ios:f894c1fe62074d01bfa280',
    messagingSenderId: '393576484737',
    projectId: 'dietifyy-66388',
    storageBucket: 'dietifyy-66388.firebasestorage.app',
    iosClientId: '393576484737-762pbsgs7fjq2enm8fckq4ckemp1q09n.apps.googleusercontent.com',
    iosBundleId: 'com.example.dietifyy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaxcJK5FYO2RINmUjQ6xPu067_lFqzJSw',
    appId: '1:393576484737:web:624f7d502912a224bfa280',
    messagingSenderId: '393576484737',
    projectId: 'dietifyy-66388',
    authDomain: 'dietifyy-66388.firebaseapp.com',
    storageBucket: 'dietifyy-66388.firebasestorage.app',
    measurementId: 'G-M83HMVCN01',
  );

}